name: dphoc
description: A new Flutter project.

# Version et autres configurations...

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  path_provider: ^2.1.5
  connectivity_plus: ^4.0.1
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  googleapis: ^10.0.0
  googleapis_auth: ^1.2.0
  # Ajoutez d'autres dépendances ici si nécessaire

dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Ajoutez cette ligne
  # Ajoutez d'autres dev_dependencies ici si nécessaire

flutter:
  uses-material-design: true

  assets:
    - assets/images/log.png
    - assets/images/wtsp.png
    - assets/fonts/4_3D.ttf
    - assets/images/manager.png
    - assets/images/mdrs.png
    - assets/data/contacts_primaire.json
    - assets/data/contacts_college.json
    - assets/data/contacts_lycee.json
    - assets/data/contacts_services.json
    - assets/data/contacts_inspectors.json
    - assets/credentials.json

  fonts:
    - family: "4_3D"
      fonts:
        - asset: "assets/fonts/4_3D.ttf"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"